### ISSUE TITLE
Palm collision in reverse causes an instant trigger

### ISSUE THREAD

**Issue by foxotic** [Janooba/immersive-interactions#6]
https://github.com/Janooba/immersive-interactions/assets/24598398/a2c8019d-d3e1-4f27-952a-0fcfedbb230b

Description:
Seems like when the palm collider comes at a button from reverse it will activate the switch as if it was pressed down, so it will activate immediately on palm enter from reverse but additionally trigger multiple times if the entire hand passes through , exits, and re-enters palm first.

Steps to reproduce:
Enable full hand collision
Pass your hand into the button collision, and completely through it while still aligned
Pull your hand directly back ensuring the palm collider enters the button first

**Comment by Janooba** [comment]
Potentially fixed in `v0.2.6-beta.3`. Please re-open if it still needs some work
